node {
  stage('build & deploy') {
    openshiftBuild bldCfg: 'nodejs-ex',
      namespace: 'pruebas',
      showBuildLogs: 'true'
    openshiftVerifyDeployment depCfg: 'nodejs-ex',
      namespace: 'pruebas'
  }
}
